/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CitaVacunacionData;
import AccesoADatos.CiudadanoData;
import Entidades.CitaVacunacion;
import Entidades.Ciudadano;
import javax.swing.JOptionPane;

/**
 *
 * @Alex Anders
 */
public class CargarCitaView extends javax.swing.JInternalFrame {

    private CiudadanoData cd = new CiudadanoData(); //se instancia un ciudadanoData
    private Ciudadano ciudadano = null;             // una instancia de ciudadano inicializado en null.
    private CitaVacunacionData cvd = new CitaVacunacionData();
    private CitaVacunacion cita = null;
    public CargarCitaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNombreCompleto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTPatologiaBase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTAmbitoLaboral = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCBCentroDeVacunacion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jDCFechaCita = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jCBCodigoRefuerzo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jRBColocada = new javax.swing.JRadioButton();
        jCBDosis = new javax.swing.JComboBox<>();
        jBLimpiar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTDocumento = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(142, 170, 189));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/min_salud (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Completo");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Celular");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Patologia Base");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Ambito Laboral");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Centro de Vacunacion");

        jCBCentroDeVacunacion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCBCentroDeVacunacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro de Vacunacion 1.", "Centro de Vacunacion 2.", "Centro de Vacunacion 3.", "Centro de Vacunacion 4.", "Centro de Vacunacion 5." }));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de Cita");

        jDCFechaCita.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Codigo de Refuerzo");

        jCBCodigoRefuerzo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCBCodigoRefuerzo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Aplicacion.", "2 Aplicacion.", "3 Aplicacion." }));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Dosis");

        jRBColocada.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jRBColocada.setText("(Colocada)");

        jCBDosis.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jCBDosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-ARNm (Pfiser)", "2-mRNA-1273 (Moderna)", "3-ChAdOx1-s (AstraSeneca)", "4-BBIBP-Corv (Sinopharm)", "5-Gam-Covid-VacM (Sputnik)" }));

        jBLimpiar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escoba.png"))); // NOI18N
        jBLimpiar.setText("Limpiar");

        jBGuardar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardar-datos_1.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBModificar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editar.png"))); // NOI18N
        jBModificar.setText("Modificar");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel11.setText("CARGAR CITAS DE VACUNACION");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setText("Documento");

        jBBuscar.setBackground(new java.awt.Color(195, 227, 250));
        jBBuscar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa.png"))); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jBLimpiar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCBCentroDeVacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDCFechaCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBCodigoRefuerzo, 0, 221, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBBuscar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBModificar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBGuardar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jRBColocada)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jCBDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTNombreCompleto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTCelular, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTPatologiaBase, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTAmbitoLaboral, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTPatologiaBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTAmbitoLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBCentroDeVacunacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDCFechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCBCodigoRefuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRBColocada)
                    .addComponent(jCBDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLimpiar)
                    .addComponent(jBGuardar)
                    .addComponent(jBModificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("www.argentina.gob.ar");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // boton buscar dni llena los text field de nombre,email,celular,patologia y ambito laboral
        try {
            int dni = Integer.parseInt(jTDocumento.getText());
            if (jTDocumento.getText().length() == 10 && jTDocumento.getText().matches("[0-9]+")||(jTCelular.getText().length()==10 && jTCelular.getText().matches("[0-9]"))||(jTEmail.getText().contentEquals("@"))) {
                ciudadano = cd.buscarCiudadanoDni(dni);
                jTNombreCompleto.setText(ciudadano.getNombreCompleto());
                jTEmail.setText(ciudadano.getEmail());
                jTCelular.setText(ciudadano.getCelular());
                jTPatologiaBase.setText(ciudadano.getPatologia());
                jTAmbitoLaboral.setText(ciudadano.getAmbitoTrabajo());
            } else {
                JOptionPane.showMessageDialog(this, "Numero de documento incompleto");
            }
        } catch (NumberFormatException nbe) {
            JOptionPane.showMessageDialog(this, "Debe ingresar números en el campo DNI." + nbe);
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(this, "El ciudadano no existe." + npe);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // BOTON GUARDAR CITAVACUNACION
//         if (cita== null) {
//                cita = new CitaVacunacion(fechaHoraCita,fechaHoraColoca);
//                cita
//
//            } else {
//                alumno.setDni(dni);
//                alumno.setApellido(apellido);
//                alumno.setNombre(nombre);
//                alumno.setFechaNacimiento(fechaNac);
//                alumno.setEstado(jRBEstado.isSelected());
//                ad.modificarAlumno(alumno);
//            }
    }//GEN-LAST:event_jBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JComboBox<String> jCBCentroDeVacunacion;
    private javax.swing.JComboBox<String> jCBCodigoRefuerzo;
    private javax.swing.JComboBox<String> jCBDosis;
    private com.toedter.calendar.JDateChooser jDCFechaCita;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JRadioButton jRBColocada;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTAmbitoLaboral;
    private javax.swing.JTextField jTCelular;
    private javax.swing.JTextField jTDocumento;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNombreCompleto;
    private javax.swing.JTextField jTPatologiaBase;
    // End of variables declaration//GEN-END:variables

//METODO PARA HACER  VISIBLE LA VENTANA DE CITA VACUNACION CUANDO ESTE LA VISTA PRINCIPAL
//HACER ACCION PERFOMER Y PEGAR ESTE CODIGO EN LA VISTA PRINCIPAL
//    private void jMenuItemActionPerfomer(java.awt.event.ActionEvent evt){
//    jDesktopPane2.removeAll();
//    jDesktopPane2.repaint();
//    CargarCitaview ccw = new CargarCitaview();
//    ccw.setVisible(true);
//    jDesktopPane2.add(ccw);
//    jDesktopPane2.movefront(ccw);
//    }
    
    
    


}
