
package Vistas;

import java.awt.Color;

public class Principal extends javax.swing.JFrame {

    public int xMouse, yMouse;
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackGround = new javax.swing.JPanel();
        jPSuperior = new javax.swing.JPanel();
        jPBotonCerrar = new javax.swing.JPanel();
        jLCerrar = new javax.swing.JLabel();
        jPanelLateral = new javax.swing.JPanel();
        jPanelBoton1 = new javax.swing.JPanel();
        jLabelBoton1 = new javax.swing.JLabel();
        jPanelBoton2 = new javax.swing.JPanel();
        jLabelBoton2 = new javax.swing.JLabel();
        jPanelBoton3 = new javax.swing.JPanel();
        jLabelBoton3 = new javax.swing.JLabel();
        jPanelBoton4 = new javax.swing.JPanel();
        jLabelBoton4 = new javax.swing.JLabel();
        jLLogoProyecto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLLogoministerio = new javax.swing.JLabel();
        jLImagenFondo = new javax.swing.JLabel();
        jDEscritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPSuperior.setOpaque(false);
        jPSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPSuperiorMouseDragged(evt);
            }
        });
        jPSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPSuperiorMousePressed(evt);
            }
        });

        jPBotonCerrar.setBackground(java.awt.Color.lightGray);
        jPBotonCerrar.setPreferredSize(new java.awt.Dimension(32, 32));

        jLCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jLCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCerrar.setText("x");
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.setPreferredSize(new java.awt.Dimension(32, 32));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBotonCerrarLayout = new javax.swing.GroupLayout(jPBotonCerrar);
        jPBotonCerrar.setLayout(jPBotonCerrarLayout);
        jPBotonCerrarLayout.setHorizontalGroup(
            jPBotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPBotonCerrarLayout.setVerticalGroup(
            jPBotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPSuperiorLayout = new javax.swing.GroupLayout(jPSuperior);
        jPSuperior.setLayout(jPSuperiorLayout);
        jPSuperiorLayout.setHorizontalGroup(
            jPSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSuperiorLayout.createSequentialGroup()
                .addContainerGap(848, Short.MAX_VALUE)
                .addComponent(jPBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPSuperiorLayout.setVerticalGroup(
            jPSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBotonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPBackGround.add(jPSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 30));

        jPanelLateral.setBackground(new java.awt.Color(50, 71, 138));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(240, 427));
        jPanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBoton1.setBackground(new java.awt.Color(195, 227, 250));

        jLabelBoton1.setForeground(new java.awt.Color(0, 51, 153));
        jLabelBoton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoton1.setText("Cargar Ciudadano");
        jLabelBoton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBoton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBoton1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBoton1Layout = new javax.swing.GroupLayout(jPanelBoton1);
        jPanelBoton1.setLayout(jPanelBoton1Layout);
        jPanelBoton1Layout.setHorizontalGroup(
            jPanelBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelBoton1Layout.setVerticalGroup(
            jPanelBoton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPanelBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 40));

        jPanelBoton2.setBackground(new java.awt.Color(174, 215, 245));

        jLabelBoton2.setForeground(new java.awt.Color(0, 51, 153));
        jLabelBoton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoton2.setText("jLabelBoton2");
        jLabelBoton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBoton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBoton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBoton2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBoton2Layout = new javax.swing.GroupLayout(jPanelBoton2);
        jPanelBoton2.setLayout(jPanelBoton2Layout);
        jPanelBoton2Layout.setHorizontalGroup(
            jPanelBoton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelBoton2Layout.setVerticalGroup(
            jPanelBoton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPanelBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        jPanelBoton3.setBackground(new java.awt.Color(167, 206, 235));

        jLabelBoton3.setForeground(new java.awt.Color(0, 51, 153));
        jLabelBoton3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoton3.setText("jLabelBoton3");
        jLabelBoton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBoton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBoton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBoton3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBoton3Layout = new javax.swing.GroupLayout(jPanelBoton3);
        jPanelBoton3.setLayout(jPanelBoton3Layout);
        jPanelBoton3Layout.setHorizontalGroup(
            jPanelBoton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelBoton3Layout.setVerticalGroup(
            jPanelBoton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPanelBoton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        jPanelBoton4.setBackground(new java.awt.Color(122, 184, 225));

        jLabelBoton4.setForeground(new java.awt.Color(0, 51, 153));
        jLabelBoton4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoton4.setText("jLabelBoton4");
        jLabelBoton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBoton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBoton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBoton4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBoton4Layout = new javax.swing.GroupLayout(jPanelBoton4);
        jPanelBoton4.setLayout(jPanelBoton4Layout);
        jPanelBoton4Layout.setHorizontalGroup(
            jPanelBoton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanelBoton4Layout.setVerticalGroup(
            jPanelBoton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBoton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPanelBoton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 40));

        jLLogoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LogoVacunAr2.png"))); // NOI18N
        jPanelLateral.add(jLLogoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 90));

        jPBackGround.add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        jPanel1.setBackground(new java.awt.Color(73, 122, 178));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jPBackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 220, 427));

        jLLogoministerio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/min_salud (1).png"))); // NOI18N
        jPBackGround.add(jLLogoministerio, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 368, 110, 50));

        jLImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.jpg"))); // NOI18N
        jPBackGround.add(jLImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jDEscritorio.setPreferredSize(new java.awt.Dimension(640, 427));

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jPBackGround.add(jDEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSuperiorMousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPSuperiorMousePressed

    private void jPSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPSuperiorMouseDragged

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseExited
        // TODO add your handling code here:
        jPBotonCerrar.setBackground(Color.LIGHT_GRAY);
        jLCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseEntered
        // TODO add your handling code here:
        jPBotonCerrar.setBackground(Color.red);
        jLCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jLabelBoton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton1MouseEntered
        // TODO add your handling code here:
        jPanelBoton1.setBackground(new Color(207, 64, 32));
        jLabelBoton1.setForeground(Color.white);
    }//GEN-LAST:event_jLabelBoton1MouseEntered

    private void jLabelBoton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton1MouseExited
        // TODO add your handling code here:
        jPanelBoton1.setBackground(new Color(195,227,250));
        jLabelBoton1.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLabelBoton1MouseExited

    private void jLabelBoton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton2MouseEntered
        // TODO add your handling code here:
        jPanelBoton2.setBackground(new Color(207, 64, 32));
        jLabelBoton2.setForeground(Color.white);
    }//GEN-LAST:event_jLabelBoton2MouseEntered

    private void jLabelBoton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton2MouseExited
        // TODO add your handling code here:
        jPanelBoton2.setBackground(new Color(174,215,245));
        jLabelBoton2.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLabelBoton2MouseExited

    private void jLabelBoton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton3MouseEntered
        // TODO add your handling code here:
        jPanelBoton3.setBackground(new Color(207, 64, 32));
        jLabelBoton3.setForeground(Color.white);
    }//GEN-LAST:event_jLabelBoton3MouseEntered

    private void jLabelBoton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton3MouseExited
        // TODO add your handling code here:
        jPanelBoton3.setBackground(new Color(167,206,235));
        jLabelBoton3.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLabelBoton3MouseExited

    private void jLabelBoton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton4MouseEntered
        // TODO add your handling code here:
        jPanelBoton4.setBackground(new Color(207, 64, 32));
        jLabelBoton4.setForeground(Color.white);
    }//GEN-LAST:event_jLabelBoton4MouseEntered

    private void jLabelBoton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBoton4MouseExited
        // TODO add your handling code here:
        jPanelBoton4.setBackground(new Color(122,184,225));
        jLabelBoton4.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLabelBoton4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLImagenFondo;
    private javax.swing.JLabel jLLogoProyecto;
    private javax.swing.JLabel jLLogoministerio;
    private javax.swing.JLabel jLabelBoton1;
    private javax.swing.JLabel jLabelBoton2;
    private javax.swing.JLabel jLabelBoton3;
    private javax.swing.JLabel jLabelBoton4;
    private javax.swing.JPanel jPBackGround;
    private javax.swing.JPanel jPBotonCerrar;
    private javax.swing.JPanel jPSuperior;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBoton1;
    private javax.swing.JPanel jPanelBoton2;
    private javax.swing.JPanel jPanelBoton3;
    private javax.swing.JPanel jPanelBoton4;
    private javax.swing.JPanel jPanelLateral;
    // End of variables declaration//GEN-END:variables
}
