
package Vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class Principal extends javax.swing.JFrame {

    public int xMouse, yMouse;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPCargarCiudadano.setVisible(false);
        jPCargarVacuna.setVisible(false);
        jPCargarLaboratorio.setVisible(false);
        jPCargarCita.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackGround = new javax.swing.JPanel();
        jPBarraSuperior = new javax.swing.JPanel();
        jPBotonCerrar = new javax.swing.JPanel();
        jLCerrar = new javax.swing.JLabel();
        jLLogoProyecto = new javax.swing.JLabel();
        jPanelLateral = new javax.swing.JPanel();
        jPBotonCiudadano = new javax.swing.JPanel();
        jLBotonCiudadano = new javax.swing.JLabel();
        jPBotonVacuna = new javax.swing.JPanel();
        jLBotonVacuna = new javax.swing.JLabel();
        jPBotonLaboratorio = new javax.swing.JPanel();
        jLBotonLaboratorio = new javax.swing.JLabel();
        jPBotonCita = new javax.swing.JPanel();
        jLBotonCita = new javax.swing.JLabel();
        jPCargarCiudadano = new javax.swing.JPanel();
        jLCargarCiudadano = new javax.swing.JLabel();
        jPCargarVacuna = new javax.swing.JPanel();
        jLCargarVacuna = new javax.swing.JLabel();
        jPCargarLaboratorio = new javax.swing.JPanel();
        jLCargarLaboratorio = new javax.swing.JLabel();
        jPCargarCita = new javax.swing.JPanel();
        jLCargarCita = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Recursos/fondo.jpg"));
        Image imagenFondo = icon.getImage();
        jDEscritorio = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(imagenFondo, 0, 0, 970, 660,this);
            }
        };
        jLLogoministerio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPBackGround.setBackground(new java.awt.Color(255, 255, 255));
        jPBackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBarraSuperior.setAlignmentX(0.0F);
        jPBarraSuperior.setAlignmentY(0.0F);
        jPBarraSuperior.setOpaque(false);
        jPBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPBarraSuperiorMouseDragged(evt);
            }
        });
        jPBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPBarraSuperiorMousePressed(evt);
            }
        });

        jPBotonCerrar.setBackground(java.awt.Color.lightGray);
        jPBotonCerrar.setPreferredSize(new java.awt.Dimension(32, 32));

        jLCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jLCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCerrar.setText("x");
        jLCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCerrar.setPreferredSize(new java.awt.Dimension(32, 32));
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBotonCerrarLayout = new javax.swing.GroupLayout(jPBotonCerrar);
        jPBotonCerrar.setLayout(jPBotonCerrarLayout);
        jPBotonCerrarLayout.setHorizontalGroup(
            jPBotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPBotonCerrarLayout.setVerticalGroup(
            jPBotonCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPBarraSuperiorLayout = new javax.swing.GroupLayout(jPBarraSuperior);
        jPBarraSuperior.setLayout(jPBarraSuperiorLayout);
        jPBarraSuperiorLayout.setHorizontalGroup(
            jPBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBarraSuperiorLayout.createSequentialGroup()
                .addContainerGap(1178, Short.MAX_VALUE)
                .addComponent(jPBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPBarraSuperiorLayout.setVerticalGroup(
            jPBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBotonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPBackGround.add(jPBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 30));

        jLLogoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LogoVacunAr.png"))); // NOI18N
        jPBackGround.add(jLLogoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 90));

        jPanelLateral.setBackground(new java.awt.Color(50, 71, 138));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(240, 427));
        jPanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBotonCiudadano.setBackground(new java.awt.Color(195, 227, 250));

        jLBotonCiudadano.setForeground(new java.awt.Color(0, 51, 153));
        jLBotonCiudadano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBotonCiudadano.setText("Gestionar Ciudadanos");
        jLBotonCiudadano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBotonCiudadano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBotonCiudadanoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBotonCiudadanoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBotonCiudadanoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBotonCiudadanoLayout = new javax.swing.GroupLayout(jPBotonCiudadano);
        jPBotonCiudadano.setLayout(jPBotonCiudadanoLayout);
        jPBotonCiudadanoLayout.setHorizontalGroup(
            jPBotonCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonCiudadano, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPBotonCiudadanoLayout.setVerticalGroup(
            jPBotonCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonCiudadano, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPBotonCiudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        jPBotonVacuna.setBackground(new java.awt.Color(174, 215, 245));

        jLBotonVacuna.setForeground(new java.awt.Color(0, 51, 153));
        jLBotonVacuna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBotonVacuna.setText("Gestionar Vacunas");
        jLBotonVacuna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBotonVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBotonVacunaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBotonVacunaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBotonVacunaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBotonVacunaLayout = new javax.swing.GroupLayout(jPBotonVacuna);
        jPBotonVacuna.setLayout(jPBotonVacunaLayout);
        jPBotonVacunaLayout.setHorizontalGroup(
            jPBotonVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPBotonVacunaLayout.setVerticalGroup(
            jPBotonVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPBotonVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        jPBotonLaboratorio.setBackground(new java.awt.Color(167, 206, 235));

        jLBotonLaboratorio.setForeground(new java.awt.Color(0, 51, 153));
        jLBotonLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBotonLaboratorio.setText("Gestionar Laboratorios");
        jLBotonLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBotonLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBotonLaboratorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBotonLaboratorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBotonLaboratorioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBotonLaboratorioLayout = new javax.swing.GroupLayout(jPBotonLaboratorio);
        jPBotonLaboratorio.setLayout(jPBotonLaboratorioLayout);
        jPBotonLaboratorioLayout.setHorizontalGroup(
            jPBotonLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPBotonLaboratorioLayout.setVerticalGroup(
            jPBotonLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPBotonLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 40));

        jPBotonCita.setBackground(new java.awt.Color(122, 184, 225));

        jLBotonCita.setForeground(new java.awt.Color(0, 51, 153));
        jLBotonCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBotonCita.setText("Gestionar Citas");
        jLBotonCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBotonCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBotonCitaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLBotonCitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLBotonCitaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPBotonCitaLayout = new javax.swing.GroupLayout(jPBotonCita);
        jPBotonCita.setLayout(jPBotonCitaLayout);
        jPBotonCitaLayout.setHorizontalGroup(
            jPBotonCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonCita, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPBotonCitaLayout.setVerticalGroup(
            jPBotonCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLBotonCita, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanelLateral.add(jPBotonCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 40));

        jPBackGround.add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 660));

        jPCargarCiudadano.setBackground(new java.awt.Color(122, 184, 225));

        jLCargarCiudadano.setForeground(new java.awt.Color(0, 51, 153));
        jLCargarCiudadano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCargarCiudadano.setText("Cargar Ciudadano");
        jLCargarCiudadano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCargarCiudadano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCargarCiudadanoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCargarCiudadanoLayout = new javax.swing.GroupLayout(jPCargarCiudadano);
        jPCargarCiudadano.setLayout(jPCargarCiudadanoLayout);
        jPCargarCiudadanoLayout.setHorizontalGroup(
            jPCargarCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarCiudadano, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPCargarCiudadanoLayout.setVerticalGroup(
            jPCargarCiudadanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarCiudadano, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPBackGround.add(jPCargarCiudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 240, 40));

        jPCargarVacuna.setBackground(new java.awt.Color(167, 206, 235));

        jLCargarVacuna.setForeground(new java.awt.Color(0, 51, 153));
        jLCargarVacuna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCargarVacuna.setText("Cargar Vacuna");
        jLCargarVacuna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCargarVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCargarVacunaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCargarVacunaLayout = new javax.swing.GroupLayout(jPCargarVacuna);
        jPCargarVacuna.setLayout(jPCargarVacunaLayout);
        jPCargarVacunaLayout.setHorizontalGroup(
            jPCargarVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPCargarVacunaLayout.setVerticalGroup(
            jPCargarVacunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPBackGround.add(jPCargarVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 240, 40));

        jPCargarLaboratorio.setBackground(new java.awt.Color(195, 227, 250));

        jLCargarLaboratorio.setForeground(new java.awt.Color(0, 51, 153));
        jLCargarLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCargarLaboratorio.setText("Cargar Laboratorio");
        jLCargarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCargarLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCargarLaboratorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCargarLaboratorioLayout = new javax.swing.GroupLayout(jPCargarLaboratorio);
        jPCargarLaboratorio.setLayout(jPCargarLaboratorioLayout);
        jPCargarLaboratorioLayout.setHorizontalGroup(
            jPCargarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPCargarLaboratorioLayout.setVerticalGroup(
            jPCargarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPBackGround.add(jPCargarLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 240, 40));

        jPCargarCita.setBackground(new java.awt.Color(174, 215, 245));

        jLCargarCita.setForeground(new java.awt.Color(0, 51, 153));
        jLCargarCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCargarCita.setText("Cargar Cita");
        jLCargarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLCargarCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCargarCitaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCargarCitaLayout = new javax.swing.GroupLayout(jPCargarCita);
        jPCargarCita.setLayout(jPCargarCitaLayout);
        jPCargarCitaLayout.setHorizontalGroup(
            jPCargarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPCargarCitaLayout.setVerticalGroup(
            jPCargarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCargarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPBackGround.add(jPCargarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 240, 40));

        jDEscritorio.setOpaque(false);
        jDEscritorio.setPreferredSize(new java.awt.Dimension(640, 427));

        jLLogoministerio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/min_salud (1).png"))); // NOI18N

        jDEscritorio.setLayer(jLLogoministerio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDEscritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLLogoministerio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDEscritorioLayout.createSequentialGroup()
                .addContainerGap(604, Short.MAX_VALUE)
                .addComponent(jLLogoministerio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPBackGround.add(jDEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 970, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBarraSuperiorMousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPBarraSuperiorMousePressed

    private void jPBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPBarraSuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPBarraSuperiorMouseDragged

    private void jLCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseExited
        // TODO add your handling code here:
        jPBotonCerrar.setBackground(Color.LIGHT_GRAY);
        jLCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLCerrarMouseExited

    private void jLCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseEntered
        // TODO add your handling code here:
        jPBotonCerrar.setBackground(Color.red);
        jLCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLCerrarMouseEntered

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jLBotonCiudadanoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonCiudadanoMouseEntered
        // TODO add your handling code here:
        jPBotonCiudadano.setBackground(new Color(207, 64, 32));
        jLBotonCiudadano.setForeground(Color.white);
    }//GEN-LAST:event_jLBotonCiudadanoMouseEntered

    private void jLBotonCiudadanoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonCiudadanoMouseExited
        // TODO add your handling code here:
        jPBotonCiudadano.setBackground(new Color(195,227,250));
        jLBotonCiudadano.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLBotonCiudadanoMouseExited

    private void jLBotonVacunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonVacunaMouseEntered
        // TODO add your handling code here:
        jPBotonVacuna.setBackground(new Color(207, 64, 32));
        jLBotonVacuna.setForeground(Color.white);
    }//GEN-LAST:event_jLBotonVacunaMouseEntered

    private void jLBotonVacunaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonVacunaMouseExited
        // TODO add your handling code here:
        jPBotonVacuna.setBackground(new Color(174,215,245));
        jLBotonVacuna.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLBotonVacunaMouseExited

    private void jLBotonLaboratorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonLaboratorioMouseEntered
        // TODO add your handling code here:
        jPBotonLaboratorio.setBackground(new Color(207, 64, 32));
        jLBotonLaboratorio.setForeground(Color.white);
    }//GEN-LAST:event_jLBotonLaboratorioMouseEntered

    private void jLBotonLaboratorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonLaboratorioMouseExited
        // TODO add your handling code here:
        jPBotonLaboratorio.setBackground(new Color(167,206,235));
        jLBotonLaboratorio.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLBotonLaboratorioMouseExited

    private void jLBotonCitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonCitaMouseEntered
        // TODO add your handling code here:
        jPBotonCita.setBackground(new Color(207, 64, 32));
        jLBotonCita.setForeground(Color.white);
    }//GEN-LAST:event_jLBotonCitaMouseEntered

    private void jLBotonCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonCitaMouseExited
        // TODO add your handling code here:
        jPBotonCita.setBackground(new Color(122,184,225));
        jLBotonCita.setForeground(new Color(0, 51, 53));
    }//GEN-LAST:event_jLBotonCitaMouseExited

    private void jLBotonCiudadanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonCiudadanoMouseClicked
        // TODO add your handling code here:
        if (jPCargarCiudadano.isVisible()) {
            jPCargarCiudadano.setVisible(false);
        } else {
            jPCargarCiudadano.setVisible(true);
            jPCargarVacuna.setVisible(false);
            jPCargarLaboratorio.setVisible(false);
            jPCargarCita.setVisible(false);
        }
    }//GEN-LAST:event_jLBotonCiudadanoMouseClicked

    private void jLBotonVacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonVacunaMouseClicked
        // TODO add your handling code here:
        if (jPCargarVacuna.isVisible()) {
            jPCargarVacuna.setVisible(false);
        } else {
            jPCargarCiudadano.setVisible(false);
            jPCargarVacuna.setVisible(true);
            jPCargarLaboratorio.setVisible(false);
            jPCargarCita.setVisible(false);
        }
    }//GEN-LAST:event_jLBotonVacunaMouseClicked

    private void jLCargarVacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCargarVacunaMouseClicked
        // TODO add your handling code here:
        jPCargarVacuna.setVisible(false);
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        Cargar_Vacuna cv = new Cargar_Vacuna();
        cv.setVisible(true);
        jDEscritorio.add(cv).setLocation(30, 30);
        jDEscritorio.moveToFront(cv);
    }//GEN-LAST:event_jLCargarVacunaMouseClicked

    private void jLCargarCiudadanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCargarCiudadanoMouseClicked
        // TODO add your handling code here:
        jPCargarCiudadano.setVisible(false);
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        GestionarCiudadano cc = new GestionarCiudadano();
        cc.setVisible(true);
        jDEscritorio.add(cc).setLocation(30, 30);
        jDEscritorio.moveToFront(cc);
    }//GEN-LAST:event_jLCargarCiudadanoMouseClicked

    private void jLBotonLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonLaboratorioMouseClicked
        // TODO add your handling code here:
         if (jPCargarLaboratorio.isVisible()) {
            jPCargarLaboratorio.setVisible(false);
        } else {
            jPCargarCiudadano.setVisible(false);
            jPCargarVacuna.setVisible(false);
            jPCargarLaboratorio.setVisible(true);
            jPCargarCita.setVisible(false);
        }
    }//GEN-LAST:event_jLBotonLaboratorioMouseClicked

    private void jLBotonCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonCitaMouseClicked
        // TODO add your handling code here:
         if (jPCargarCita.isVisible()) {
            jPCargarCita.setVisible(false);
        } else {
            jPCargarCiudadano.setVisible(false);
            jPCargarVacuna.setVisible(false);
            jPCargarLaboratorio.setVisible(false);
            jPCargarCita.setVisible(true);
        }
    }//GEN-LAST:event_jLBotonCitaMouseClicked

    private void jLCargarLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCargarLaboratorioMouseClicked
        // TODO add your handling code here:
        jPCargarLaboratorio.setVisible(false);
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        CargarLaboratorio cl = new CargarLaboratorio();
        cl.setVisible(true);
        jDEscritorio.add(cl).setLocation(30, 30);
        jDEscritorio.moveToFront(cl);
    }//GEN-LAST:event_jLCargarLaboratorioMouseClicked

    private void jLCargarCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCargarCitaMouseClicked
        // TODO add your handling code here:
        jPCargarCita.setVisible(false);
        jDEscritorio.removeAll();
        jDEscritorio.repaint();
        CargarCitaView ccv = new CargarCitaView();
        ccv.setVisible(true);
        jDEscritorio.add(ccv).setLocation(30, 30);
        jDEscritorio.moveToFront(ccv);
    }//GEN-LAST:event_jLCargarCitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JLabel jLBotonCita;
    private javax.swing.JLabel jLBotonCiudadano;
    private javax.swing.JLabel jLBotonLaboratorio;
    private javax.swing.JLabel jLBotonVacuna;
    private javax.swing.JLabel jLCargarCita;
    private javax.swing.JLabel jLCargarCiudadano;
    private javax.swing.JLabel jLCargarLaboratorio;
    private javax.swing.JLabel jLCargarVacuna;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLLogoProyecto;
    private javax.swing.JLabel jLLogoministerio;
    private javax.swing.JPanel jPBackGround;
    private javax.swing.JPanel jPBarraSuperior;
    private javax.swing.JPanel jPBotonCerrar;
    private javax.swing.JPanel jPBotonCita;
    private javax.swing.JPanel jPBotonCiudadano;
    private javax.swing.JPanel jPBotonLaboratorio;
    private javax.swing.JPanel jPBotonVacuna;
    private javax.swing.JPanel jPCargarCita;
    private javax.swing.JPanel jPCargarCiudadano;
    private javax.swing.JPanel jPCargarLaboratorio;
    private javax.swing.JPanel jPCargarVacuna;
    private javax.swing.JPanel jPanelLateral;
    // End of variables declaration//GEN-END:variables
}
